# working with python Libraries using import statement

In [1]:
import math

In [6]:
math.pi  #pie constant

3.141592653589793

In [5]:
math.e       #exponential constant

2.718281828459045

In [7]:
math.inf     #infinite num

inf

In [9]:
math.ceil(7.8)             #equivalent to the Approximation 

8

In [12]:
math.floor(4.6)           #equivant to Roundoff

4

In [15]:
float_list =  [0.1, 0.1, 0.1, 0,1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [14]:
sum(float_list)

1.9000000000000006

In [16]:
math.fsum(float_list)

1.8

In [17]:
math.gcd(30, 20)

10

In [18]:
math.gcd(3343, 223)

1

In [19]:
!pip install numpy

In [20]:
import numpy as np

In [21]:
some_list = [1, 2, 3, 4, 5, 6, 7]

type(some_list)

list

In [22]:
some_array = np.array(some_list)     #converts the list into array

type(some_array)

numpy.ndarray

In [23]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
ones_array = np.ones(5)

ones_array

array([1., 1., 1., 1., 1.])

In [28]:
range_array = np.arange(8)

range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

you can reshape the dimension of any array using the reshape  keyword

In [29]:
reshape_array = range_array.reshape(2,4)

reshape_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
reshape_array = range_array.reshape(4, 2)

reshape_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

you can generate random numbers to fill an array using the random function. NOTE : The values will be between 0 and 1

In [33]:
random_array = np.random.random((4, 5))

random_array

array([[0.21382365, 0.34820605, 0.32833606, 0.46826883, 0.52022854],
       [0.19590652, 0.01452689, 0.85455641, 0.72583115, 0.86175905],
       [0.04285319, 0.27493475, 0.05917641, 0.84496518, 0.07047403],
       [0.06060263, 0.28697395, 0.31437457, 0.98672724, 0.16326793]])

In [35]:
mean_val = np.mean(range_array)

mean_val

3.5

In [38]:
median_val = np.median(range_array)

median_val

3.5

In [40]:
std = np.std(range_array)
    
std 

2.29128784747792

PANDAS: When working with data in a CSV file its best to use pandas

In [41]:
!pip install pandas

the data frame is the data type of pandas, it is used to hold data in rows and columns

In [42]:
import pandas as pd

In [43]:
df = pd.DataFrame({
                   'name': ['John', 'Alice', 'Bob', 'Rilean', 'Rob'],
                   'gender': ['male', 'female', 'male', 'female', 'male'],
                   'age': [45, 20, 30, 14, 67]
                 })

In [44]:
df

name  gender  age
0    John    male   45
1   Alice  female   20
2     Bob    male   30
3  Rilean  female   14
4     Rob    male   67

In [48]:
 df.describe()


age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

df.describe fnction gives all summary of the mean, minimum, maximum, 1st, 2nd  3rd percentile, count standard dev.

In [49]:
subset_df = df[['name', 'age']]
subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Rilean   14
4     Rob   67